---
title: "VFT/SpAM data processing"
output: html_document
date: "2025-07-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries
```{r}
#Toolboxes
library(tidyverse)
library(dplyr)
library(jsonlite)
library(dplyr)
library(tidyr)
library(jsonlite)
library(stringr)
```

## Importing Data
```{r}
#Importing participant csv data file: 
#datafile <- read_csv("filepath") where filepath is the location of the csv file

#Pilot participant csv data file:
datafile <- read_csv("../Data/raw_data/reddit_data.csv") %>%filter(subject!="BYK6XPTX") #participant who completed it 2x

#Viewing the data file in separate tab:
#View(datafile)

#just complete runs 
# Note: some people didn't click final save data button, but did finish the study

```

##Cleaning Subreddit/Interest Data
```{r}
#checking if each subject completed each domain, only keeping data from those who completed all domains
good_domain_counts <- datafile %>%
    filter(
    task == "VFT",
   !domain %in% c("subreddits", "interest")) %>% 
  group_by(subject,run_id) %>%
  summarise(unique_domains = n_distinct(domain))%>%
  filter(unique_domains==5)

#only keep good participants
datafile_clean<-datafile%>%filter(subject %in% good_domain_counts$subject)

#ID dropped p's
bad_domain_counts <- datafile %>%
    filter(
    task == "VFT",
   !domain %in% c("subreddits", "interest")) %>% 
  group_by(subject,run_id) %>%
  summarise(unique_domains = n_distinct(domain))%>%
  filter(unique_domains<5)
bad_domain_counts


#to isolate data on participants interests and subreddits interacted with 
organized_interest_data <- datafile_clean %>% 
  filter(domain %in% c("subreddits", "interest")) %>%
  filter(!is.na(tagged_responses), tagged_responses != "", tagged_responses != "[]") %>%
  rowwise() %>%
  mutate(parsed_responses = list(fromJSON(tagged_responses))) %>%
  ungroup() %>%
  unnest_longer(parsed_responses) %>%
  unnest_wider(parsed_responses, names_sep = "_")

subreddit_data <- organized_interest_data%>%
  filter(domain == "subreddits") %>%
  select(subject, parsed_responses_response, parsed_responses_tag) %>%
  rename(subreddit_responses = parsed_responses_response,
         tag = parsed_responses_tag)
View(subreddit_data)
write_csv(subreddit_data, "../Data/raw_data/subreddit_data.csv")

interests_data <- organized_interest_data%>%
  filter(domain == "interest")%>%
  select(subject, parsed_responses_response, parsed_responses_tag) %>%
  rename(interests_responses = parsed_responses_response,
         tag = parsed_responses_tag)
View(interests_data)
write_csv(interests_data, "../Data/raw_data/interests_data.csv")
  
```

##Cleaning Fluency Data 
```{r}
safe_fromJSON <- function(x) {
  tryCatch(fromJSON(x), error = function(e) NULL)
}
#to make data analysis through Forager easier:
organized_fluency <- datafile_clean %>% #initiates dplyr pipeline
  filter(
    task == "VFT",
   !domain %in% c("furniture-practice", "subreddits", "interest"),
   !is.na(tagged_responses),
   !is.na(response_times)
    ) %>% 
  mutate(
    parsed_responses = map(tagged_responses, safe_fromJSON),
    parsed_times = map(response_times, safe_fromJSON)
  ) %>%
  filter(
    !map_lgl(parsed_responses, is.null),
    !map_lgl(parsed_times, is.null)
  ) %>%
  unnest_longer(parsed_responses, indices_to = "idx") %>%
  unnest_longer(parsed_times, indices_to = "idx_time") %>%
  filter(idx == idx_time) %>%
  unnest_wider(parsed_responses, names_sep = "_") %>%
  transmute(
    subject,
    response = parsed_responses_response,
    entry_number = parsed_responses_tag,
    response_times = parsed_times,
    domain
    ) %>%
  arrange(subject, domain, entry_number)

write_csv(organized_fluency, "../Data/raw_data/organized_fluency.csv") 
View(organized_fluency)

```

##Cleaning SpAM Data
```{r}

organized_spam <- datafile_clean %>%
    filter(subject!="DUBYYHYX" & domain!="college_majors")%>% #this trial was incomplete in the downloaded data for some reason
  filter(
    #subject %in% good_domain_counts$subject,
    task == "SpAM",
    !is.na(droppedwords),
    droppedwords != "[]",
    droppedwords != "",
    domain != "furniture-practice"
  ) %>%
  rowwise() %>%
  mutate(droppedwords = list(fromJSON(droppedwords))) %>%
  filter(length(droppedwords) > 0) %>%
  unnest_longer(droppedwords) %>%
  unnest_wider(droppedwords) %>%
  ungroup() %>%
  group_by(subject, domain, id) %>%
  slice_tail(n = 1) %>%                     # keep only most recent position per id
  ungroup() %>%
  mutate(entry_number = as.numeric(str_remove(id, "word-"))) %>%
  arrange(subject, domain, entry_number) %>%
  group_by(subject, domain) %>%              # only pair up within domain
  mutate(
    x  = x_norm,
    y  = y_norm,
    word1 = word,
    x1 = x,
    y1 = y,
    word2 = lead(word),
    x2    = lead(x),
    y2    = lead(y),
    pair  = if_else(is.na(word2), NA_character_,
                           stringr::str_c(word1, word2, sep = ", "))
  ) %>%
  ungroup() %>%
  select(subject, word, entry_number, x, y, domain, pair, word1, x1, y1, word2, x2, y2)

```

##Calculating Euclidean Distance for SpAM Data
```{r}
organized_spam <- organized_spam %>%
  group_by(domain, subject) %>%
  mutate(
    x_next = lead(x),
    y_next = lead(y),
    euclidean_distance = sqrt((x_next - x)^2 + (y_next - y)^2))%>%
  ungroup()%>%
  select(-x_next, -y_next)
View(organized_spam)
write_csv(organized_spam, "../Data/raw_data/organized_spam.csv")
```

## Cleaning demographics data
```{r}
cols_to_select <- c("run_id", "age", "gender", "education", "question_order", "race", "hispanic", "english", "additional_languages","long_NewsArticles","long_FictionBooks","long_NonFictionBooks","long_EssaysBlogsNewsletters","long_Podcasts","social_Twitter","social_Facebook","social_TikTok","social_Reddit","social_YouTube","social_Instagram","social_Snapchat")

optional_cols <- c("first_language", "age_learned_english")
cols_to_select <- c(cols_to_select, optional_cols[optional_cols %in% colnames(datafile)])

demographics_cleaned <- datafile_clean %>%
  filter(typeoftrial %in% c("demographics","long_form_exposure","social_media_exposure"),
         run_id %in% good_domain_counts$run_id) %>%
  select(all_of(cols_to_select)) %>%
  filter(!if_all(everything(), is.na)) %>%
  mutate(
    age = as.numeric(age),
    education = as.numeric(education),
    gender = as.character(gender),
    race = as.character(race),
    english = as.character(english),
    additional_languages = as.character(additional_languages),
    across(any_of(c("first_language", "age_learned_english")), as.character)
  ) %>%
  group_by(run_id) %>%
  fill(everything(), .direction = "downup") %>%
  slice(1) %>%
  ungroup() %>%
  mutate(across(c(age, gender, education, race, hispanic, english,additional_languages,long_NewsArticles,long_FictionBooks,long_NonFictionBooks,long_EssaysBlogsNewsletters,long_Podcasts,social_Twitter,social_Facebook,social_TikTok,social_Reddit,social_YouTube,
                  social_Instagram,social_Snapchat),
                ~ifelse(. == "" | is.na(.), "blank", .)))

write_csv(demographics_cleaned, "../Data/cleaned_data/demographics_data.csv")
View(demographics_cleaned)




```

# Cleaning Fluency Interest & Fluency Estimate

```{r}
fluency_cleaned = read_csv("../Data/cleaned_data/fluency_data.csv") %>%
  group_by(Subject, domain) %>% count()

fluency_interest = datafile %>% 
  filter(subject %in% good_domain_counts$subject & 
           typeoftrial %in% c("VFT_category_interest", "VFT_estimate")) %>%
  select(subject, domain, typeoftrial, response, rt)


fluency_interest_wide <- fluency_interest %>%
  mutate(typeoftrial = recode(typeoftrial, 
                         "VFT_category_interest" = "interest",
                         "VFT_estimate" = "estimate")) %>%
  pivot_wider(id_cols = c(subject, domain), names_from = typeoftrial,
    values_from = c(response, rt), names_glue = "{typeoftrial}_{.value}")%>%
  rename(Subject= subject) %>%
  left_join(fluency_cleaned) %>%
  rename(fluency_score= n)

write_csv(fluency_interest, "../Data/cleaned_data/fluency_interest_estimate.csv")
```

